.ifndef _DEBUGSCREEN_H
_DEBUGSCREEN_H = 1
.macro    dbgmsg msgchar, b
          saveall
          lda #msgchar-'A'+1
          jsr _debug_screen_write_char
          lda #58
          jsr _debug_screen_write_char
          lda b
          jsr _debug_screen_write_byte
          lda #32
          jsr _debug_screen_write_char
          resall
.endmacro
.macro    dbgmsg1 msgchar
          saveall
          lda #msgchar-'A'+1
          jsr _debug_screen_write_char
          resall
.endmacro

.endif
