.include "system.mac"
.macro      debug_string s
            .local mystring
.data
mystring:
            .asciiz s
.code
            mov #mystring, ptr_string
            jsr _debug_string
.endmacro

.macro       debug_number mem
            saveall
            .if (.match (.left (1, {mem}), X))
            txa
            .elseif (.match (.left (1, {mem}), Y))
            tya
            .else
            lda mem
            .endif
            jsr _debug_number
            resall
.endmacro
