.ifdef TESTS

.macro assert_eq condition_name, val1, val2
.local not_equal, done
          myprintf condition_name
.if (.match (.left (1, {val1}), #))
            lda #(.right (.tcount ({val1})-1, {val1}))
.else
            lda val1
.endif
.if (.match (.left (1, {val2}), #))
            cmp #(.right (.tcount ({val2})-1, {val2}))
.else
            cmp val2
.endif
          bne not_equal
          myprintf "passed"
          jmp done
not_equal:          
          myprintf "failed"
done:     
.endmacro
.endif
